Custom ids
tommilligan/mdbook-admonish pull request #144
Opened 2023-10-24 19:39 UTC by Sky9x

- You can now set custom CSS ids for admonishment blocks with the `id` field.
- You can now customize the default CSS id prefix (default is `"admonition-"`).

Feel free to nitpick everything (doc wording etc)

2023-10-24 20:11 UTC, Sky9x commented on src/resolve.rs
> +            defaults
maybe the original if statement looks better? (changed cuz of clippy)

```rust
let css_id = if let Some(verbatim) = id {
    Some(CssIdType::Verbatim(verbatim))
} else if let Some(prefix) = &defaults.css_id_prefix {
    Some(CssIdType::Prefix(prefix.clone()))
} else {
    None
};
```

2023-11-10 22:26 UTC, tommilligan commented
Hi - just commenting briefly to say thanks for the contribution! I'm mid review, got interrupted by some Life, but hope to pick up in the next week. On board with the idea though 👍

2023-11-15 22:03 UTC, tommilligan requested changes
This is excellent work, thank you very much!

I made changes while I was reviewing. I've rebased and pushed this to a new branch `sky9-review` (as I can't update `Sky9x:main`). You can see the review changes here: https://github.com/tommilligan/mdbook-admonish/compare/main...sky9-review

Mostly this was just moving code around to make types match up, after my comments. If you're happy with the changes I've made, please update this PR to match and we can get it merged. Also happy to chat more about any of the changes if you have further thoughts.

2023-11-15 22:03 UTC, tommilligan commented on book/src/reference.md
> +- `default.css-id-prefix` (optional, default: `"admonition-"`): The default css id prefix to add to the id of all blocks. Ignored on blocks with an `id` field.
`css-id-prefix` should be `css_id_prefix` everywhere, to be consistent with existing snake case options like `on_failure`

2023-11-15 22:03 UTC, tommilligan commented on src/types.rs
> +pub(crate) enum CssIdType {
No need to use `Type` in the name here, `CssId` is fine (you're containing the actual id data in here as well)
```suggestion
pub(crate) enum CssId {
```

2023-11-15 22:03 UTC, tommilligan commented on src/render.rs
> +    pub(crate) css_id: Option<CssIdType>,
We should lose the `Option` here, as each block will definitely have an id - we should know it at this point.
```suggestion
    pub(crate) css_id: CssIdType,
```

This will force some refactoring elsewhere, which should help move a few things around.

2023-11-15 22:03 UTC, tommilligan commented on .gitignore
> +/.idea/
You should add this to your global `.gitignore` settings as it's editor specific - not project specific.

2023-11-15 22:03 UTC, tommilligan commented on src/resolve.rs
> +/// Make the first letter of `input` uppercase.
Amazing :sweat_smile: thank you

2023-11-15 22:07 UTC, Sky9x commented on .gitignore
> +/.idea/
theres a global gitignore??

2023-11-15 22:21 UTC, tommilligan commented on .gitignore
> +/.idea/
There is indeed - if you search for `.gitignore_global` on this page there's more info: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration

2023-11-15 22:22 UTC, Sky9x commented on .gitignore
> +/.idea/
i did not know that, thank you!

2023-11-15 22:27 UTC, Sky9x commented
strange that you cant edit my branch as i have "allow edits by maintainers" enabled but :shrug:

resolved merge conflicts with upstream/main, accepted all your changed, and added my final nitpicks

im done unless you have anything else otherwise its good to go

2023-11-15 22:34 UTC, merged