Add collapsible support
tommilligan/mdbook-admonish pull request #26
Opened 2022-05-04 12:05 UTC by gggto

2022-05-04 12:20 UTC, gggto commented
@tommilligan do you have any insight?

2022-05-04 13:30 UTC, schungx commented
> The links to the admonition titles interfere with the open/close interaction. Clicking on the title doesn't open the box, which is counter-intuitive.

This is going to need some thinking through... The link is there in order to generate the <kbd>Copy Link Address</kbd> context menu choice to copy the URL.  Without it, it is hard to get a link to a particular part of the document.

However, you're also correct that the expected behavior upon clicking is to toggle the collapsing.

Maybe a custom `onclick`?

2022-05-15 07:55 UTC, tommilligan commented
Sorry for the slow reply, been a busy couple of weeks for me.

The collapsible support looks really good, thanks for taking a stab at it!

I think I will move anchor link generation to an appear-on-hover icon, like a lot of sites (including doc.rs for code items) do:

![anchor-link-hover](https://user-images.githubusercontent.com/12255914/168462939-7372ac75-9bbc-4850-b255-2a4fd42ceb8c.gif)

I think this is more discoverable anyway, and then leaves the header bar free to be clicked on to expand the dropdown/the title to contain links, etc.

This should allow this PR to be merged as is, after rebase and unit tests added.

2022-05-18 10:33 UTC, tommilligan commented
@gggto now https://github.com/tommilligan/mdbook-admonish/pull/27 is merged, title links should no longer be an issue

2022-05-18 11:20 UTC, gggto commented
Thank you a lot! However, I'm not confident enough in my git-fu to properly fix the conflict between main and this fork, without screwing the git history or opening unwanted PR or whatever. The conflict looks really easy to solve though, so I'm sure we're not to far from merging.

What would you like me to do from there?

2022-05-18 11:25 UTC, tommilligan commented
No worries, thanks for you work so far. I'll work through the conflict now and let you know what needed fixing. Then I'll add a review with any outstanding tasks.

2022-05-18 11:43 UTC, tommilligan commented
For future reference, the conflict was reasonably simple to fix. You could run the following locally to reproduce what I did:

- add the upstream repo (this one) as a new remote: `git remote add upstream https://github.com/tommilligan/mdbook-admonish`
- fetch upstream's changes: `git fetch upstream`
- run a rebase on the upstream main branch: `git checkout main && git rebase upstream/main`
- fix the conflict. Git is pointing out that I moved the `<a>` tag at the same time as you did your changes
```rust
                Cow::Owned(format!(
<<<<<<< HEAD
                    r##"<{title_block} class="admonition-title">

{title}

<a class="admonition-anchor-link" href="#{ANCHOR_ID_PREFIX}-{anchor_id}"></a>
</{title_block}>
=======
<a class="admonition-anchor-link" href="#{ANCHOR_ID_PREFIX}-{anchor_id}">

{title}

</a>
>>>>>>> Add collapsible support
"##
```
so we can resolve as
```rust
                Cow::Owned(format!(
                    r##"<{title_block} class="admonition-title">

{title}

<a class="admonition-anchor-link" href="#{ANCHOR_ID_PREFIX}-{anchor_id}"></a>
</{title_block}>
"##
```
- save your changes and finish the rebase with: `git add -u && git rebase --continue`
- this should get you to a point where the tests pass (`cargo test`)
- then push back to your own repository; you have to add `-f` to force overwrite the remote after a rebase: `git push -f`

2022-05-18 12:17 UTC, tommilligan requested changes
Looks really good, thanks for taking this on. I have some changes locally I will push onto your branch.

2022-05-18 12:17 UTC, tommilligan commented on src/config/mod.rs
> +    is_collapsible: bool,
small nit: `is_collapsible` is generally superfluous, just `collapsible` is fine throughout

2022-05-18 12:17 UTC, tommilligan commented on compile_assets/scss/admonition.scss
> +summary {
We should be specific we're only styling _our_ summaries here, there could be others on the page in user content.

For example:

```suggestion
summary.admonition-title {
```

2022-05-18 12:17 UTC, tommilligan commented on compile_assets/scss/admonition.scss
> +  details[open] > &::after {
```suggestion
  details[open].admonition > &::after {
```

2022-05-18 12:17 UTC, tommilligan commented on compile_assets/scss/admonition.scss
> +    url("data:image/svg+xml;charset=utf-8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path d='M8.59 16.58 13.17 12 8.59 7.41 10 6l6 6-6 6-1.41-1.42Z'/></svg>");
I think this looks perfect! Thanks very much.

For reference, we have:

![image](https://user-images.githubusercontent.com/12255914/169036688-4ff5eae5-c639-47a9-a3f6-b61fb0f45de5.png)

and

![image](https://user-images.githubusercontent.com/12255914/169036728-d5dd69fd-ff37-43d0-aec8-94d6797e691f.png)

2022-05-18 12:22 UTC, tommilligan commented
Alright, updated and squashed. Just waiting for CI to run.

The final step was adding some docs and unit/integration tests (as we're adding new html elements I wanted to check that interaction too).

2022-05-18 12:23 UTC, tommilligan approved these changes

2022-05-18 12:24 UTC, merged